### ISSUE TITLE
Support for Guardian Farm lag removal

### ISSUE THREAD

**Issue by James76931** [NyaaCat/Yasui#10]
Hi.

I've been having a lot of lag issues recently whenever a Guardian farm is in use on my server.
Could it please be possible for a new feature to be added to help deal with the lag produced by these farms?

Thanks,
James

**Comment by ReinWD** [comment]
Could you please paste a `Paper Timing` or `Spark samper report` so we can locate the issue?

**Comment by ReinWD** [comment]
If the creature spawning action is too expensive, try PaperMC and configure player-specific spawning.
If AI of Guardian is causing lag, just make a confuguration in yasui.
Newer version of Spigot seems can let ***NERFED*** entity to have the ability to swim.
Confirmed that NERFED entity can drop down from water and can be moved by water.
Try latest dev build & latest version of Spigot/PaperMC.
