### ISSUE TITLE
1.12 support

### ISSUE THREAD

**Issue by columb** [NyaaCat/Yasui#3]
I do suspect that Yasui uses Paper API implemented in 1.13+ versions but if there is a way to backport it it would be so freacking awesome.

**Comment by phoenixlzx** [comment]
Unfortunately there is no way to backport all yasui features to older versions where Paper/Spigot have not implement the API yet.

But you can use yasui version 1.13 which is built against 1.12.2 and get the basic AI suppress feature for your server.
https://github.com/NyaaCat/Yasui/releases/download/master-v1.13/Yasui-master-v1.13.jar
You need NC 4.1 as well.
https://github.com/NyaaCat/NyaaCore/releases/download/v4.1.163-mc1.12/NyaaCore-v4.1.163-mc1.12.jar
